---
name: Fork Update PR

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 10 * * 1'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  checkov:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'mpaucar'
    name: Checkov
    uses: MPaucar/GitHub-Actions/.github/workflows/checkov.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
