---
name: Groovy Shared Library

on:
  push:
    branches:
      - master
      - main
    paths:
      - src/**/*.groovy
      - vars/*.groovy
  pull_request:
    branches:
      - master
      - main
    paths:
      - src/**/*.groovy
      - vars/*.groovy
  workflow_dispatch:

permissions:
  contents: read

jobs:
  groovyc:
    if: github.event.repository.fork == false
    name: Groovy Shared Library
